name: Docker Image CI

on:
  push:
    branches:
      - master

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  IMAGE_NAME: sebbia/androidsdk-docker

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Docker Hub description
      uses: meeDamian/sync-readme@v1.0.6
      with:
        user: ${{secrets.DOCKER_USER}}
        pass: ${{secrets.DOCKER_PASSWORD}}
        slug: sebbia/androidsdk-docker
        readme: ./README.md
        description: true

  build-30_0_3-java11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file 30.0.3-java11/Dockerfile --tag ${IMAGE_NAME}:30.0.3-java11
    - name: Push image to Docker Hub
      run: |
        docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
        docker push ${IMAGE_NAME}:30.0.3-java11

